/*
 * UNAF NPU ISA Specification Header
 *
 * AUTO-GENERATED by specs/scripts/gen_all.py -- DO NOT EDIT
 * Source: specs/definitions/[all].yaml
 * Generated: 2026-03-05 00:18:39
 */

#ifndef UNAF_NPU_SPEC_H
#define UNAF_NPU_SPEC_H

#if defined(__KERNEL__) && defined(__linux__)
    #include <linux/types.h>
#else
    #include <stdint.h>
#endif

#ifdef __cplusplus
#define _Static_assert static_assert
#endif

#define NPU_INST_SIZE 64

/* ================================================================== */
/* NPU Instruction Opcodes                                           */
/* ================================================================== */
typedef enum {
    NPU_OP_NOP                = 0x00,  /* No operation - pipeline bubble / alignment */
    NPU_OP_HALT               = 0x01,  /* Stop NPU execution, raise completion interrupt */
    NPU_OP_ADD                = 0x10,  /* Element-wise addition: dst[i] = src_a[i] + src_b[i] */
    NPU_OP_SUB                = 0x11,  /* Element-wise subtraction: dst[i] = src_a[i] - src_b[i] */
    NPU_OP_MUL                = 0x12,  /* Element-wise multiplication: dst[i] = src_a[i] * src_b[i] */
    NPU_OP_DIV                = 0x13,  /* Element-wise division: dst[i] = src_a[i] / src_b[i] */
    NPU_OP_MATMUL             = 0x20,  /* Matrix multiplication: dst = src_a @ src_b */
    NPU_OP_CONV2D             = 0x30,  /* 2D convolution: dst = conv2d(input, weight) */
    NPU_OP_DEPTHWISE_CONV     = 0x31,  /* Depthwise convolution (MobileNet) */
    NPU_OP_RELU               = 0x40,  /* Element-wise ReLU: dst[i] = max(0, src[i]) */
    NPU_OP_SIGMOID            = 0x41,  /* Sigmoid activation: dst[i] = 1 / (1 + exp(-src[i])) */
    NPU_OP_TANH               = 0x42,  /* Tanh activation: dst[i] = tanh(src[i]) */
    NPU_OP_GELU               = 0x43,  /* GELU activation (Transformer standard) */
    NPU_OP_SOFTMAX            = 0x45,  /* Softmax along last axis: dst = softmax(src) */
    NPU_OP_BATCHNORM          = 0x50,  /* Batch normalization: dst = (src - mean) / sqrt(var + eps) * gamma + beta */
    NPU_OP_LAYERNORM          = 0x51,  /* Layer normalization (Transformer) */
    NPU_OP_MAXPOOL            = 0x60,  /* Max pooling 2D */
    NPU_OP_AVGPOOL            = 0x61,  /* Average pooling 2D */
    NPU_OP_REDUCE_SUM         = 0x70,  /* Sum reduction along specified axis */
    NPU_OP_REDUCE_MEAN        = 0x71,  /* Mean reduction along specified axis */
    NPU_OP_REDUCE_MAX         = 0x72,  /* Max reduction along specified axis */
    NPU_OP_LOAD               = 0x80,  /* DMA transfer: host memory -> NPU local SRAM */
    NPU_OP_STORE              = 0x81,  /* DMA transfer: NPU local SRAM -> host memory */
    NPU_OP_TRANSPOSE          = 0x90,  /* Tensor transpose (permute axes) */
    NPU_OP_RESHAPE            = 0x91,  /* Tensor reshape (metadata-only if contiguous) */
    NPU_OP_CONCAT             = 0x92,  /* Concatenate tensors along specified axis */
    NPU_OP_SPLIT              = 0x93,  /* Split tensor along specified axis */
} npu_opcode_t;

/* ================================================================== */
/* ACTIVATION Instructions                                   */
/* ================================================================== */

/* Element-wise ReLU: dst[i] = max(0, src[i]) */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0x40) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode for future variants */
    uint8_t flags;                       /* +0x02: [0]=fp16 [1]=leaky (use alpha) */
    uint8_t reserved0;                   /* +0x03: Reserved */
    uint16_t alpha_fp16;                 /* +0x04: Leaky ReLU alpha (fp16 encoded), 0 if standard */
    uint16_t reserved1;                  /* +0x06: Reserved */
    uint64_t src_addr;                   /* +0x08: NPU-local address of input */
    uint64_t dst_addr;                   /* +0x10: NPU-local address of output */
    uint32_t num_elements;               /* +0x18: Total number of elements */
    uint32_t reserved2;                  /* +0x1C: Reserved */
    uint8_t reserved_pad[32];            /* +0x20: Padding to 64 bytes */
} npu_inst_relu_t;

_Static_assert(sizeof(npu_inst_relu_t) == NPU_INST_SIZE,
              "npu_inst_relu_t must be 64 bytes");

/* Sigmoid activation: dst[i] = 1 / (1 + exp(-src[i])) */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0x41) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode */
    uint8_t flags;                       /* +0x02: [0]=fp16 */
    uint8_t reserved0;                   /* +0x03: Reserved */
    uint32_t reserved1;                  /* +0x04: Reserved */
    uint64_t src_addr;                   /* +0x08: NPU-local address of input */
    uint64_t dst_addr;                   /* +0x10: NPU-local address of output */
    uint32_t num_elements;               /* +0x18: Total number of elements */
    uint32_t reserved2;                  /* +0x1C: Reserved */
    uint8_t reserved_pad[32];            /* +0x20: Padding to 64 bytes */
} npu_inst_sigmoid_t;

_Static_assert(sizeof(npu_inst_sigmoid_t) == NPU_INST_SIZE,
              "npu_inst_sigmoid_t must be 64 bytes");

/* Tanh activation: dst[i] = tanh(src[i]) */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0x42) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode */
    uint8_t flags;                       /* +0x02: [0]=fp16 */
    uint8_t reserved0;                   /* +0x03: Reserved */
    uint32_t reserved1;                  /* +0x04: Reserved */
    uint64_t src_addr;                   /* +0x08: NPU-local address of input */
    uint64_t dst_addr;                   /* +0x10: NPU-local address of output */
    uint32_t num_elements;               /* +0x18: Total number of elements */
    uint32_t reserved2;                  /* +0x1C: Reserved */
    uint8_t reserved_pad[32];            /* +0x20: Padding to 64 bytes */
} npu_inst_tanh_t;

_Static_assert(sizeof(npu_inst_tanh_t) == NPU_INST_SIZE,
              "npu_inst_tanh_t must be 64 bytes");

/* GELU activation (Transformer standard) */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0x43) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode */
    uint8_t flags;                       /* +0x02: [0]=fp16 */
    uint8_t reserved0;                   /* +0x03: Reserved */
    uint32_t reserved1;                  /* +0x04: Reserved */
    uint64_t src_addr;                   /* +0x08: NPU-local address of input */
    uint64_t dst_addr;                   /* +0x10: NPU-local address of output */
    uint32_t num_elements;               /* +0x18: Total number of elements */
    uint32_t reserved2;                  /* +0x1C: Reserved */
    uint8_t reserved_pad[32];            /* +0x20: Padding to 64 bytes */
} npu_inst_gelu_t;

_Static_assert(sizeof(npu_inst_gelu_t) == NPU_INST_SIZE,
              "npu_inst_gelu_t must be 64 bytes");

/* Softmax along last axis: dst = softmax(src) */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0x45) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode for future variants */
    uint8_t flags;                       /* +0x02: [0]=fp16 */
    uint8_t reserved0;                   /* +0x03: Reserved */
    uint32_t reserved1;                  /* +0x04: Reserved */
    uint64_t src_addr;                   /* +0x08: NPU-local address of input */
    uint64_t dst_addr;                   /* +0x10: NPU-local address of output */
    uint32_t batch_size;                 /* +0x18: Number of vectors (batch) */
    uint32_t axis_size;                  /* +0x1C: Elements per vector (softmax axis dim) */
    uint8_t reserved_pad[32];            /* +0x20: Padding to 64 bytes */
} npu_inst_softmax_t;

_Static_assert(sizeof(npu_inst_softmax_t) == NPU_INST_SIZE,
              "npu_inst_softmax_t must be 64 bytes");

/* ================================================================== */
/* ARITHMETIC Instructions                                   */
/* ================================================================== */

/* Element-wise addition: dst[i] = src_a[i] + src_b[i] */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0x10) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode for future variants */
    uint8_t flags;                       /* +0x02: [0]=fp16 [1]=broadcast_b */
    uint8_t reserved0;                   /* +0x03: Reserved */
    uint32_t reserved1;                  /* +0x04: Reserved */
    uint64_t src_a_addr;                 /* +0x08: NPU-local address of tensor A */
    uint64_t src_b_addr;                 /* +0x10: NPU-local address of tensor B */
    uint64_t dst_addr;                   /* +0x18: NPU-local address of output */
    uint32_t num_elements;               /* +0x20: Total number of elements */
    uint32_t reserved2;                  /* +0x24: Reserved */
    uint8_t reserved_pad[24];            /* +0x28: Padding to 64 bytes */
} npu_inst_add_t;

_Static_assert(sizeof(npu_inst_add_t) == NPU_INST_SIZE,
              "npu_inst_add_t must be 64 bytes");

/* Element-wise subtraction: dst[i] = src_a[i] - src_b[i] */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0x11) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode */
    uint8_t flags;                       /* +0x02: [0]=fp16 [1]=broadcast_b */
    uint8_t reserved0;                   /* +0x03: Reserved */
    uint32_t reserved1;                  /* +0x04: Reserved */
    uint64_t src_a_addr;                 /* +0x08: NPU-local address of tensor A */
    uint64_t src_b_addr;                 /* +0x10: NPU-local address of tensor B */
    uint64_t dst_addr;                   /* +0x18: NPU-local address of output */
    uint32_t num_elements;               /* +0x20: Total number of elements */
    uint32_t reserved2;                  /* +0x24: Reserved */
    uint8_t reserved_pad[24];            /* +0x28: Padding to 64 bytes */
} npu_inst_sub_t;

_Static_assert(sizeof(npu_inst_sub_t) == NPU_INST_SIZE,
              "npu_inst_sub_t must be 64 bytes");

/* Element-wise multiplication: dst[i] = src_a[i] * src_b[i] */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0x12) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode */
    uint8_t flags;                       /* +0x02: [0]=fp16 [1]=broadcast_b */
    uint8_t reserved0;                   /* +0x03: Reserved */
    uint32_t reserved1;                  /* +0x04: Reserved */
    uint64_t src_a_addr;                 /* +0x08: NPU-local address of tensor A */
    uint64_t src_b_addr;                 /* +0x10: NPU-local address of tensor B */
    uint64_t dst_addr;                   /* +0x18: NPU-local address of output */
    uint32_t num_elements;               /* +0x20: Total number of elements */
    uint32_t reserved2;                  /* +0x24: Reserved */
    uint8_t reserved_pad[24];            /* +0x28: Padding to 64 bytes */
} npu_inst_mul_t;

_Static_assert(sizeof(npu_inst_mul_t) == NPU_INST_SIZE,
              "npu_inst_mul_t must be 64 bytes");

/* Element-wise division: dst[i] = src_a[i] / src_b[i] */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0x13) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode */
    uint8_t flags;                       /* +0x02: [0]=fp16 [1]=broadcast_b */
    uint8_t reserved0;                   /* +0x03: Reserved */
    uint32_t reserved1;                  /* +0x04: Reserved */
    uint64_t src_a_addr;                 /* +0x08: NPU-local address of tensor A */
    uint64_t src_b_addr;                 /* +0x10: NPU-local address of tensor B */
    uint64_t dst_addr;                   /* +0x18: NPU-local address of output */
    uint32_t num_elements;               /* +0x20: Total number of elements */
    uint32_t reserved2;                  /* +0x24: Reserved */
    uint8_t reserved_pad[24];            /* +0x28: Padding to 64 bytes */
} npu_inst_div_t;

_Static_assert(sizeof(npu_inst_div_t) == NPU_INST_SIZE,
              "npu_inst_div_t must be 64 bytes");

/* ================================================================== */
/* CONTROL Instructions                                   */
/* ================================================================== */

/* No operation - pipeline bubble / alignment */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0x00) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode for future variants */
    uint8_t flags;                       /* +0x02: Reserved flags */
    uint8_t reserved0;                   /* +0x03: Reserved */
    uint8_t reserved_pad[60];            /* +0x04: Padding to 64 bytes */
} npu_inst_nop_t;

_Static_assert(sizeof(npu_inst_nop_t) == NPU_INST_SIZE,
              "npu_inst_nop_t must be 64 bytes");

/* Stop NPU execution, raise completion interrupt */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0x01) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode for future variants */
    uint8_t flags;                       /* +0x02: Bit[0]=raise_irq */
    uint8_t reserved0;                   /* +0x03: Reserved */
    uint16_t exit_code;                  /* +0x04: Exit status passed to host */
    uint16_t reserved1;                  /* +0x06: Reserved */
    uint8_t reserved_pad[56];            /* +0x08: Padding to 64 bytes */
} npu_inst_halt_t;

_Static_assert(sizeof(npu_inst_halt_t) == NPU_INST_SIZE,
              "npu_inst_halt_t must be 64 bytes");

/* ================================================================== */
/* CONVOLUTION Instructions                                   */
/* ================================================================== */

/* 2D convolution: dst = conv2d(input, weight) */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0x30) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode for future variants */
    uint8_t flags;                       /* +0x02: [0]=fp16 [1]=relu_fused [2]=bias_en */
    uint8_t reserved0;                   /* +0x03: Reserved */
    uint8_t pad_h;                       /* +0x04: Padding height */
    uint8_t pad_w;                       /* +0x05: Padding width */
    uint8_t stride_h;                    /* +0x06: Stride height */
    uint8_t stride_w;                    /* +0x07: Stride width */
    uint64_t input_addr;                 /* +0x08: NPU-local address of input tensor */
    uint64_t weight_addr;                /* +0x10: NPU-local address of weight tensor */
    uint64_t bias_addr;                  /* +0x18: NPU-local address of bias (0 if unused) */
    uint64_t dst_addr;                   /* +0x20: NPU-local address of output tensor */
    uint16_t in_c;                       /* +0x28: Input channels */
    uint16_t in_h;                       /* +0x2A: Input height */
    uint16_t in_w;                       /* +0x2C: Input width */
    uint16_t out_c;                      /* +0x2E: Output channels */
    uint8_t kernel_h;                    /* +0x30: Kernel height */
    uint8_t kernel_w;                    /* +0x31: Kernel width */
    uint16_t reserved1;                  /* +0x32: Reserved */
    uint8_t reserved_pad[12];            /* +0x34: Padding to 64 bytes */
} npu_inst_conv2d_t;

_Static_assert(sizeof(npu_inst_conv2d_t) == NPU_INST_SIZE,
              "npu_inst_conv2d_t must be 64 bytes");

/* Depthwise convolution (MobileNet) */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0x31) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode */
    uint8_t flags;                       /* +0x02: [0]=fp16 [1]=relu_fused */
    uint8_t reserved0;                   /* +0x03: Reserved */
    uint8_t pad_h;                       /* +0x04: Padding height */
    uint8_t pad_w;                       /* +0x05: Padding width */
    uint8_t stride_h;                    /* +0x06: Stride height */
    uint8_t stride_w;                    /* +0x07: Stride width */
    uint64_t input_addr;                 /* +0x08: NPU-local address of input */
    uint64_t weight_addr;                /* +0x10: NPU-local address of weight (C×K×K) */
    uint64_t dst_addr;                   /* +0x18: NPU-local address of output */
    uint16_t channels;                   /* +0x20: Number of channels */
    uint16_t in_h;                       /* +0x22: Input height */
    uint16_t in_w;                       /* +0x24: Input width */
    uint8_t kernel_h;                    /* +0x26: Kernel height */
    uint8_t kernel_w;                    /* +0x27: Kernel width */
    uint32_t reserved1;                  /* +0x28: Reserved */
    uint8_t reserved_pad[20];            /* +0x2C: Padding to 64 bytes */
} npu_inst_depthwise_conv_t;

_Static_assert(sizeof(npu_inst_depthwise_conv_t) == NPU_INST_SIZE,
              "npu_inst_depthwise_conv_t must be 64 bytes");

/* ================================================================== */
/* LAYOUT Instructions                                   */
/* ================================================================== */

/* Tensor transpose (permute axes) */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0x90) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode */
    uint8_t flags;                       /* +0x02: [0]=fp16 */
    uint8_t num_dims;                    /* +0x03: Number of dimensions (2-4) */
    uint8_t perm_0;                      /* +0x04: Permutation axis 0 */
    uint8_t perm_1;                      /* +0x05: Permutation axis 1 */
    uint8_t perm_2;                      /* +0x06: Permutation axis 2 */
    uint8_t perm_3;                      /* +0x07: Permutation axis 3 */
    uint64_t src_addr;                   /* +0x08: NPU-local address of input */
    uint64_t dst_addr;                   /* +0x10: NPU-local address of output */
    uint32_t dim_0;                      /* +0x18: Size of dimension 0 */
    uint32_t dim_1;                      /* +0x1C: Size of dimension 1 */
    uint32_t dim_2;                      /* +0x20: Size of dimension 2 */
    uint32_t dim_3;                      /* +0x24: Size of dimension 3 */
    uint8_t reserved_pad[24];            /* +0x28: Padding to 64 bytes */
} npu_inst_transpose_t;

_Static_assert(sizeof(npu_inst_transpose_t) == NPU_INST_SIZE,
              "npu_inst_transpose_t must be 64 bytes");

/* Tensor reshape (metadata-only if contiguous) */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0x91) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode */
    uint8_t flags;                       /* +0x02: [0]=fp16 */
    uint8_t reserved0;                   /* +0x03: Reserved */
    uint32_t reserved1;                  /* +0x04: Reserved */
    uint64_t src_addr;                   /* +0x08: NPU-local address of input */
    uint64_t dst_addr;                   /* +0x10: NPU-local address of output (can be same) */
    uint32_t total_elements;             /* +0x18: Total number of elements */
    uint32_t reserved2;                  /* +0x1C: Reserved */
    uint8_t reserved_pad[32];            /* +0x20: Padding to 64 bytes */
} npu_inst_reshape_t;

_Static_assert(sizeof(npu_inst_reshape_t) == NPU_INST_SIZE,
              "npu_inst_reshape_t must be 64 bytes");

/* Concatenate tensors along specified axis */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0x92) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode */
    uint8_t flags;                       /* +0x02: [0]=fp16 */
    uint8_t axis;                        /* +0x03: Concatenation axis */
    uint8_t num_inputs;                  /* +0x04: Number of input tensors (2-8) */
    uint8_t reserved0;                   /* +0x05: Reserved */
    uint16_t reserved1;                  /* +0x06: Reserved */
    uint64_t src_addr_0;                 /* +0x08: Input tensor 0 address */
    uint64_t src_addr_1;                 /* +0x10: Input tensor 1 address */
    uint64_t dst_addr;                   /* +0x18: Output tensor address */
    uint32_t outer_size;                 /* +0x20: Elements before concat axis */
    uint16_t concat_size_0;              /* +0x24: Size of input 0 along concat axis */
    uint16_t concat_size_1;              /* +0x26: Size of input 1 along concat axis */
    uint32_t inner_size;                 /* +0x28: Elements after concat axis */
    uint32_t reserved2;                  /* +0x2C: Reserved */
    uint8_t reserved_pad[16];            /* +0x30: Padding to 64 bytes */
} npu_inst_concat_t;

_Static_assert(sizeof(npu_inst_concat_t) == NPU_INST_SIZE,
              "npu_inst_concat_t must be 64 bytes");

/* Split tensor along specified axis */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0x93) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode */
    uint8_t flags;                       /* +0x02: [0]=fp16 */
    uint8_t axis;                        /* +0x03: Split axis */
    uint8_t num_outputs;                 /* +0x04: Number of output tensors (2-8) */
    uint8_t reserved0;                   /* +0x05: Reserved */
    uint16_t reserved1;                  /* +0x06: Reserved */
    uint64_t src_addr;                   /* +0x08: Input tensor address */
    uint64_t dst_addr_0;                 /* +0x10: Output tensor 0 address */
    uint64_t dst_addr_1;                 /* +0x18: Output tensor 1 address */
    uint32_t outer_size;                 /* +0x20: Elements before split axis */
    uint16_t split_size;                 /* +0x24: Size of each split (uniform) */
    uint16_t reserved2;                  /* +0x26: Reserved */
    uint32_t inner_size;                 /* +0x28: Elements after split axis */
    uint32_t reserved3;                  /* +0x2C: Reserved */
    uint8_t reserved_pad[16];            /* +0x30: Padding to 64 bytes */
} npu_inst_split_t;

_Static_assert(sizeof(npu_inst_split_t) == NPU_INST_SIZE,
              "npu_inst_split_t must be 64 bytes");

/* ================================================================== */
/* LINALG Instructions                                   */
/* ================================================================== */

/* Matrix multiplication: dst = src_a @ src_b */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0x20) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode for future variants */
    uint8_t flags;                       /* +0x02: [0]=fp16 [1]=accumulate [2]=transpose_a [3]=transpose_b */
    uint8_t reserved0;                   /* +0x03: Reserved */
    uint32_t reserved1;                  /* +0x04: Reserved */
    uint64_t src_a_addr;                 /* +0x08: NPU-local address of matrix A */
    uint64_t src_b_addr;                 /* +0x10: NPU-local address of matrix B */
    uint64_t dst_addr;                   /* +0x18: NPU-local address of result C */
    uint32_t m;                          /* +0x20: Rows of A (and C) */
    uint32_t n;                          /* +0x24: Cols of B (and C) */
    uint32_t k;                          /* +0x28: Cols of A / Rows of B */
    uint32_t reserved2;                  /* +0x2C: Reserved */
    uint8_t reserved_pad[16];            /* +0x30: Padding to 64 bytes */
} npu_inst_matmul_t;

_Static_assert(sizeof(npu_inst_matmul_t) == NPU_INST_SIZE,
              "npu_inst_matmul_t must be 64 bytes");

/* ================================================================== */
/* MEMORY Instructions                                   */
/* ================================================================== */

/* DMA transfer: host memory -> NPU local SRAM */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0x80) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode for future variants */
    uint8_t flags;                       /* +0x02: [0]=async [1]=notify_on_complete */
    uint8_t reserved0;                   /* +0x03: Reserved */
    uint32_t reserved1;                  /* +0x04: Reserved */
    uint64_t host_addr;                  /* +0x08: Host physical/IOVA address (source) */
    uint64_t npu_addr;                   /* +0x10: NPU-local SRAM address (destination) */
    uint32_t size_bytes;                 /* +0x18: Number of bytes to transfer */
    uint32_t reserved2;                  /* +0x1C: Reserved */
    uint8_t reserved_pad[32];            /* +0x20: Padding to 64 bytes */
} npu_inst_load_t;

_Static_assert(sizeof(npu_inst_load_t) == NPU_INST_SIZE,
              "npu_inst_load_t must be 64 bytes");

/* DMA transfer: NPU local SRAM -> host memory */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0x81) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode for future variants */
    uint8_t flags;                       /* +0x02: [0]=async [1]=notify_on_complete */
    uint8_t reserved0;                   /* +0x03: Reserved */
    uint32_t reserved1;                  /* +0x04: Reserved */
    uint64_t npu_addr;                   /* +0x08: NPU-local SRAM address (source) */
    uint64_t host_addr;                  /* +0x10: Host physical/IOVA address (destination) */
    uint32_t size_bytes;                 /* +0x18: Number of bytes to transfer */
    uint32_t reserved2;                  /* +0x1C: Reserved */
    uint8_t reserved_pad[32];            /* +0x20: Padding to 64 bytes */
} npu_inst_store_t;

_Static_assert(sizeof(npu_inst_store_t) == NPU_INST_SIZE,
              "npu_inst_store_t must be 64 bytes");

/* ================================================================== */
/* NORMALIZATION Instructions                                   */
/* ================================================================== */

/* Batch normalization: dst = (src - mean) / sqrt(var + eps) * gamma + beta */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0x50) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode */
    uint8_t flags;                       /* +0x02: [0]=fp16 [1]=affine (use gamma/beta) */
    uint8_t reserved0;                   /* +0x03: Reserved */
    uint32_t epsilon_fp32;               /* +0x04: Small constant for numerical stability */
    uint64_t src_addr;                   /* +0x08: NPU-local address of input (N×C×H×W) */
    uint64_t mean_addr;                  /* +0x10: NPU-local address of mean (C) */
    uint64_t var_addr;                   /* +0x18: NPU-local address of variance (C) */
    uint64_t gamma_addr;                 /* +0x20: NPU-local address of gamma/scale (C) */
    uint64_t beta_addr;                  /* +0x28: NPU-local address of beta/bias (C) */
    uint64_t dst_addr;                   /* +0x30: NPU-local address of output */
    uint32_t num_channels;               /* +0x38: Number of channels (C) */
    uint32_t spatial_size;               /* +0x3C: H×W (elements per channel) */
} npu_inst_batchnorm_t;

_Static_assert(sizeof(npu_inst_batchnorm_t) == NPU_INST_SIZE,
              "npu_inst_batchnorm_t must be 64 bytes");

/* Layer normalization (Transformer) */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0x51) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode */
    uint8_t flags;                       /* +0x02: [0]=fp16 [1]=affine */
    uint8_t reserved0;                   /* +0x03: Reserved */
    uint32_t epsilon_fp32;               /* +0x04: Small constant */
    uint64_t src_addr;                   /* +0x08: NPU-local address of input */
    uint64_t gamma_addr;                 /* +0x10: NPU-local address of gamma (optional) */
    uint64_t beta_addr;                  /* +0x18: NPU-local address of beta (optional) */
    uint64_t dst_addr;                   /* +0x20: NPU-local address of output */
    uint32_t normalized_shape;           /* +0x28: Size of normalization dimension */
    uint32_t batch_size;                 /* +0x2C: Number of vectors to normalize */
    uint8_t reserved_pad[16];            /* +0x30: Padding to 64 bytes */
} npu_inst_layernorm_t;

_Static_assert(sizeof(npu_inst_layernorm_t) == NPU_INST_SIZE,
              "npu_inst_layernorm_t must be 64 bytes");

/* ================================================================== */
/* POOLING Instructions                                   */
/* ================================================================== */

/* Max pooling 2D */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0x60) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode */
    uint8_t flags;                       /* +0x02: [0]=fp16 */
    uint8_t reserved0;                   /* +0x03: Reserved */
    uint8_t kernel_h;                    /* +0x04: Kernel height */
    uint8_t kernel_w;                    /* +0x05: Kernel width */
    uint8_t stride_h;                    /* +0x06: Stride height */
    uint8_t stride_w;                    /* +0x07: Stride width */
    uint64_t src_addr;                   /* +0x08: NPU-local address of input */
    uint64_t dst_addr;                   /* +0x10: NPU-local address of output */
    uint16_t in_c;                       /* +0x18: Input channels */
    uint16_t in_h;                       /* +0x1A: Input height */
    uint16_t in_w;                       /* +0x1C: Input width */
    uint16_t reserved1;                  /* +0x1E: Reserved */
    uint8_t reserved_pad[32];            /* +0x20: Padding to 64 bytes */
} npu_inst_maxpool_t;

_Static_assert(sizeof(npu_inst_maxpool_t) == NPU_INST_SIZE,
              "npu_inst_maxpool_t must be 64 bytes");

/* Average pooling 2D */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0x61) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode */
    uint8_t flags;                       /* +0x02: [0]=fp16 */
    uint8_t reserved0;                   /* +0x03: Reserved */
    uint8_t kernel_h;                    /* +0x04: Kernel height */
    uint8_t kernel_w;                    /* +0x05: Kernel width */
    uint8_t stride_h;                    /* +0x06: Stride height */
    uint8_t stride_w;                    /* +0x07: Stride width */
    uint64_t src_addr;                   /* +0x08: NPU-local address of input */
    uint64_t dst_addr;                   /* +0x10: NPU-local address of output */
    uint16_t in_c;                       /* +0x18: Input channels */
    uint16_t in_h;                       /* +0x1A: Input height */
    uint16_t in_w;                       /* +0x1C: Input width */
    uint16_t reserved1;                  /* +0x1E: Reserved */
    uint8_t reserved_pad[32];            /* +0x20: Padding to 64 bytes */
} npu_inst_avgpool_t;

_Static_assert(sizeof(npu_inst_avgpool_t) == NPU_INST_SIZE,
              "npu_inst_avgpool_t must be 64 bytes");

/* ================================================================== */
/* REDUCTION Instructions                                   */
/* ================================================================== */

/* Sum reduction along specified axis */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0x70) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode */
    uint8_t flags;                       /* +0x02: [0]=fp16 [1]=keep_dims */
    uint8_t axis;                        /* +0x03: Axis to reduce (0=batch, 1=channel, 2=height, 3=width) */
    uint32_t reserved0;                  /* +0x04: Reserved */
    uint64_t src_addr;                   /* +0x08: NPU-local address of input */
    uint64_t dst_addr;                   /* +0x10: NPU-local address of output */
    uint32_t outer_size;                 /* +0x18: Elements before reduction axis */
    uint32_t reduce_size;                /* +0x1C: Size of reduction axis */
    uint32_t inner_size;                 /* +0x20: Elements after reduction axis */
    uint32_t reserved1;                  /* +0x24: Reserved */
    uint8_t reserved_pad[24];            /* +0x28: Padding to 64 bytes */
} npu_inst_reduce_sum_t;

_Static_assert(sizeof(npu_inst_reduce_sum_t) == NPU_INST_SIZE,
              "npu_inst_reduce_sum_t must be 64 bytes");

/* Mean reduction along specified axis */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0x71) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode */
    uint8_t flags;                       /* +0x02: [0]=fp16 [1]=keep_dims */
    uint8_t axis;                        /* +0x03: Axis to reduce */
    uint32_t reserved0;                  /* +0x04: Reserved */
    uint64_t src_addr;                   /* +0x08: NPU-local address of input */
    uint64_t dst_addr;                   /* +0x10: NPU-local address of output */
    uint32_t outer_size;                 /* +0x18: Elements before reduction axis */
    uint32_t reduce_size;                /* +0x1C: Size of reduction axis */
    uint32_t inner_size;                 /* +0x20: Elements after reduction axis */
    uint32_t reserved1;                  /* +0x24: Reserved */
    uint8_t reserved_pad[24];            /* +0x28: Padding to 64 bytes */
} npu_inst_reduce_mean_t;

_Static_assert(sizeof(npu_inst_reduce_mean_t) == NPU_INST_SIZE,
              "npu_inst_reduce_mean_t must be 64 bytes");

/* Max reduction along specified axis */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0x72) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode */
    uint8_t flags;                       /* +0x02: [0]=fp16 [1]=keep_dims */
    uint8_t axis;                        /* +0x03: Axis to reduce */
    uint32_t reserved0;                  /* +0x04: Reserved */
    uint64_t src_addr;                   /* +0x08: NPU-local address of input */
    uint64_t dst_addr;                   /* +0x10: NPU-local address of output */
    uint32_t outer_size;                 /* +0x18: Elements before reduction axis */
    uint32_t reduce_size;                /* +0x1C: Size of reduction axis */
    uint32_t inner_size;                 /* +0x20: Elements after reduction axis */
    uint32_t reserved1;                  /* +0x24: Reserved */
    uint8_t reserved_pad[24];            /* +0x28: Padding to 64 bytes */
} npu_inst_reduce_max_t;

_Static_assert(sizeof(npu_inst_reduce_max_t) == NPU_INST_SIZE,
              "npu_inst_reduce_max_t must be 64 bytes");

/* ================================================================== */
/* Generic Instruction (for fetch/decode)                             */
/* ================================================================== */
typedef union __attribute__((packed)) {
    uint8_t  opcode;                       /* First byte is always opcode */
    uint8_t  raw[NPU_INST_SIZE];           /* Raw byte access */
    npu_inst_nop_t                       nop;
    npu_inst_halt_t                      halt;
    npu_inst_add_t                       add;
    npu_inst_sub_t                       sub;
    npu_inst_mul_t                       mul;
    npu_inst_div_t                       div;
    npu_inst_matmul_t                    matmul;
    npu_inst_conv2d_t                    conv2d;
    npu_inst_depthwise_conv_t            depthwise_conv;
    npu_inst_relu_t                      relu;
    npu_inst_sigmoid_t                   sigmoid;
    npu_inst_tanh_t                      tanh;
    npu_inst_gelu_t                      gelu;
    npu_inst_softmax_t                   softmax;
    npu_inst_batchnorm_t                 batchnorm;
    npu_inst_layernorm_t                 layernorm;
    npu_inst_maxpool_t                   maxpool;
    npu_inst_avgpool_t                   avgpool;
    npu_inst_reduce_sum_t                reduce_sum;
    npu_inst_reduce_mean_t               reduce_mean;
    npu_inst_reduce_max_t                reduce_max;
    npu_inst_load_t                      load;
    npu_inst_store_t                     store;
    npu_inst_transpose_t                 transpose;
    npu_inst_reshape_t                   reshape;
    npu_inst_concat_t                    concat;
    npu_inst_split_t                     split;
} npu_inst_t;

_Static_assert(sizeof(npu_inst_t) == NPU_INST_SIZE,
              "npu_inst_t must be 64 bytes");

#define NPU_OPCODE_COUNT 27

#endif /* UNAF_NPU_SPEC_H */
