/*
 * UNAF NPU ISA Specification Header
 *
 * AUTO-GENERATED by specs/scripts/gen_all.py -- DO NOT EDIT
 * Source: specs/definitions/ *.yaml
 * Generated: 2026-02-21 00:07:48
 */

#ifndef UNAF_NPU_SPEC_H
#define UNAF_NPU_SPEC_H

#if defined(__KERNEL__) && defined(__linux__)
    #include <linux/types.h>
#else
    #include <stdint.h>
#endif

#ifdef __cplusplus
#define _Static_assert static_assert
#endif

#define NPU_INST_SIZE 64

/* ================================================================== */
/* NPU Instruction Opcodes                                           */
/* ================================================================== */
typedef enum {
    NPU_OP_NOP          = 0x00,  /* No operation - pipeline bubble / alignment */
    NPU_OP_HALT         = 0x01,  /* Stop NPU execution, raise completion interrupt */
    NPU_OP_MATMUL       = 0x10,  /* Matrix multiplication: dst = src_a @ src_b */
    NPU_OP_CONV2D       = 0x11,  /* 2D convolution: dst = conv2d(input, weight) */
    NPU_OP_RELU         = 0x12,  /* Element-wise ReLU: dst[i] = max(0, src[i]) */
    NPU_OP_ADD          = 0x13,  /* Element-wise addition: dst[i] = src_a[i] + src_b[i] */
    NPU_OP_SOFTMAX      = 0x14,  /* Softmax along last axis: dst = softmax(src) */
    NPU_OP_LOAD         = 0x40,  /* DMA transfer: host memory -> NPU local SRAM */
    NPU_OP_STORE        = 0x41,  /* DMA transfer: NPU local SRAM -> host memory */
} npu_opcode_t;

/* ================================================================== */
/* CONTROL Instructions                                   */
/* ================================================================== */

/* No operation - pipeline bubble / alignment */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0x00) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode for future variants */
    uint8_t flags;                       /* +0x02: Reserved flags */
    uint8_t reserved0;                   /* +0x03: Reserved */
    uint8_t reserved_pad[60];            /* +0x04: Padding to 64 bytes */
} npu_inst_nop_t;

_Static_assert(sizeof(npu_inst_nop_t) == NPU_INST_SIZE,
              "npu_inst_nop_t must be 64 bytes");

/* Stop NPU execution, raise completion interrupt */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0x01) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode for future variants */
    uint8_t flags;                       /* +0x02: Bit[0]=raise_irq */
    uint8_t reserved0;                   /* +0x03: Reserved */
    uint16_t exit_code;                  /* +0x04: Exit status passed to host */
    uint16_t reserved1;                  /* +0x06: Reserved */
    uint8_t reserved_pad[56];            /* +0x08: Padding to 64 bytes */
} npu_inst_halt_t;

_Static_assert(sizeof(npu_inst_halt_t) == NPU_INST_SIZE,
              "npu_inst_halt_t must be 64 bytes");

/* ================================================================== */
/* COMPUTE Instructions                                   */
/* ================================================================== */

/* Matrix multiplication: dst = src_a @ src_b */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0x10) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode for future variants */
    uint8_t flags;                       /* +0x02: [0]=fp16 [1]=accumulate [2]=transpose_a [3]=transpose_b */
    uint8_t reserved0;                   /* +0x03: Reserved */
    uint32_t reserved1;                  /* +0x04: Reserved */
    uint64_t src_a_addr;                 /* +0x08: NPU-local address of matrix A */
    uint64_t src_b_addr;                 /* +0x10: NPU-local address of matrix B */
    uint64_t dst_addr;                   /* +0x18: NPU-local address of result C */
    uint32_t m;                          /* +0x20: Rows of A (and C) */
    uint32_t n;                          /* +0x24: Cols of B (and C) */
    uint32_t k;                          /* +0x28: Cols of A / Rows of B */
    uint32_t reserved2;                  /* +0x2C: Reserved */
    uint8_t reserved_pad[16];            /* +0x30: Padding to 64 bytes */
} npu_inst_matmul_t;

_Static_assert(sizeof(npu_inst_matmul_t) == NPU_INST_SIZE,
              "npu_inst_matmul_t must be 64 bytes");

/* 2D convolution: dst = conv2d(input, weight) */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0x11) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode for future variants */
    uint8_t flags;                       /* +0x02: [0]=fp16 [1]=relu_fused [2]=bias_en */
    uint8_t reserved0;                   /* +0x03: Reserved */
    uint8_t pad_h;                       /* +0x04: Padding height */
    uint8_t pad_w;                       /* +0x05: Padding width */
    uint8_t stride_h;                    /* +0x06: Stride height */
    uint8_t stride_w;                    /* +0x07: Stride width */
    uint64_t input_addr;                 /* +0x08: NPU-local address of input tensor */
    uint64_t weight_addr;                /* +0x10: NPU-local address of weight tensor */
    uint64_t bias_addr;                  /* +0x18: NPU-local address of bias (0 if unused) */
    uint64_t dst_addr;                   /* +0x20: NPU-local address of output tensor */
    uint16_t in_c;                       /* +0x28: Input channels */
    uint16_t in_h;                       /* +0x2A: Input height */
    uint16_t in_w;                       /* +0x2C: Input width */
    uint16_t out_c;                      /* +0x2E: Output channels */
    uint8_t kernel_h;                    /* +0x30: Kernel height */
    uint8_t kernel_w;                    /* +0x31: Kernel width */
    uint16_t reserved1;                  /* +0x32: Reserved */
    uint8_t reserved_pad[12];            /* +0x34: Padding to 64 bytes */
} npu_inst_conv2d_t;

_Static_assert(sizeof(npu_inst_conv2d_t) == NPU_INST_SIZE,
              "npu_inst_conv2d_t must be 64 bytes");

/* Element-wise ReLU: dst[i] = max(0, src[i]) */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0x12) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode for future variants */
    uint8_t flags;                       /* +0x02: [0]=fp16 [1]=leaky (use alpha) */
    uint8_t reserved0;                   /* +0x03: Reserved */
    uint16_t alpha_fp16;                 /* +0x04: Leaky ReLU alpha (fp16 encoded), 0 if standard */
    uint16_t reserved1;                  /* +0x06: Reserved */
    uint64_t src_addr;                   /* +0x08: NPU-local address of input */
    uint64_t dst_addr;                   /* +0x10: NPU-local address of output */
    uint32_t num_elements;               /* +0x18: Total number of elements */
    uint32_t reserved2;                  /* +0x1C: Reserved */
    uint8_t reserved_pad[32];            /* +0x20: Padding to 64 bytes */
} npu_inst_relu_t;

_Static_assert(sizeof(npu_inst_relu_t) == NPU_INST_SIZE,
              "npu_inst_relu_t must be 64 bytes");

/* Element-wise addition: dst[i] = src_a[i] + src_b[i] */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0x13) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode for future variants */
    uint8_t flags;                       /* +0x02: [0]=fp16 [1]=broadcast_b */
    uint8_t reserved0;                   /* +0x03: Reserved */
    uint32_t reserved1;                  /* +0x04: Reserved */
    uint64_t src_a_addr;                 /* +0x08: NPU-local address of tensor A */
    uint64_t src_b_addr;                 /* +0x10: NPU-local address of tensor B */
    uint64_t dst_addr;                   /* +0x18: NPU-local address of output */
    uint32_t num_elements;               /* +0x20: Total number of elements */
    uint32_t reserved2;                  /* +0x24: Reserved */
    uint8_t reserved_pad[24];            /* +0x28: Padding to 64 bytes */
} npu_inst_add_t;

_Static_assert(sizeof(npu_inst_add_t) == NPU_INST_SIZE,
              "npu_inst_add_t must be 64 bytes");

/* Softmax along last axis: dst = softmax(src) */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0x14) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode for future variants */
    uint8_t flags;                       /* +0x02: [0]=fp16 */
    uint8_t reserved0;                   /* +0x03: Reserved */
    uint32_t reserved1;                  /* +0x04: Reserved */
    uint64_t src_addr;                   /* +0x08: NPU-local address of input */
    uint64_t dst_addr;                   /* +0x10: NPU-local address of output */
    uint32_t batch_size;                 /* +0x18: Number of vectors (batch) */
    uint32_t axis_size;                  /* +0x1C: Elements per vector (softmax axis dim) */
    uint8_t reserved_pad[32];            /* +0x20: Padding to 64 bytes */
} npu_inst_softmax_t;

_Static_assert(sizeof(npu_inst_softmax_t) == NPU_INST_SIZE,
              "npu_inst_softmax_t must be 64 bytes");

/* ================================================================== */
/* MEMORY Instructions                                    */
/* ================================================================== */

/* DMA transfer: host memory -> NPU local SRAM */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0x40) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode for future variants */
    uint8_t flags;                       /* +0x02: [0]=async [1]=notify_on_complete */
    uint8_t reserved0;                   /* +0x03: Reserved */
    uint32_t reserved1;                  /* +0x04: Reserved */
    uint64_t host_addr;                  /* +0x08: Host physical/IOVA address (source) */
    uint64_t npu_addr;                   /* +0x10: NPU-local SRAM address (destination) */
    uint32_t size_bytes;                 /* +0x18: Number of bytes to transfer */
    uint32_t reserved2;                  /* +0x1C: Reserved */
    uint8_t reserved_pad[32];            /* +0x20: Padding to 64 bytes */
} npu_inst_load_t;

_Static_assert(sizeof(npu_inst_load_t) == NPU_INST_SIZE,
              "npu_inst_load_t must be 64 bytes");

/* DMA transfer: NPU local SRAM -> host memory */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0x41) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode for future variants */
    uint8_t flags;                       /* +0x02: [0]=async [1]=notify_on_complete */
    uint8_t reserved0;                   /* +0x03: Reserved */
    uint32_t reserved1;                  /* +0x04: Reserved */
    uint64_t npu_addr;                   /* +0x08: NPU-local SRAM address (source) */
    uint64_t host_addr;                  /* +0x10: Host physical/IOVA address (destination) */
    uint32_t size_bytes;                 /* +0x18: Number of bytes to transfer */
    uint32_t reserved2;                  /* +0x1C: Reserved */
    uint8_t reserved_pad[32];            /* +0x20: Padding to 64 bytes */
} npu_inst_store_t;

_Static_assert(sizeof(npu_inst_store_t) == NPU_INST_SIZE,
              "npu_inst_store_t must be 64 bytes");

/* ================================================================== */
/* Generic Instruction (for fetch/decode)                             */
/* ================================================================== */
typedef union __attribute__((packed)) {
    uint8_t  opcode;                       /* First byte is always opcode */
    uint8_t  raw[NPU_INST_SIZE];           /* Raw byte access */
    npu_inst_nop_t                       nop;
    npu_inst_halt_t                      halt;
    npu_inst_matmul_t                    matmul;
    npu_inst_conv2d_t                    conv2d;
    npu_inst_relu_t                      relu;
    npu_inst_add_t                       add;
    npu_inst_softmax_t                   softmax;
    npu_inst_load_t                      load;
    npu_inst_store_t                     store;
} npu_inst_t;

_Static_assert(sizeof(npu_inst_t) == NPU_INST_SIZE,
              "npu_inst_t must be 64 bytes");

#define NPU_OPCODE_COUNT 9

#endif /* UNAF_NPU_SPEC_H */
