/*
 * UNAF LPU ISA Specification Header
 *
 * AUTO-GENERATED by specs/scripts/gen_all.py -- DO NOT EDIT
 * Source: specs/definitions/[all].yaml
 */

#ifndef UNAF_LPU_SPEC_H
#define UNAF_LPU_SPEC_H

#if defined(__KERNEL__) && defined(__linux__)
    #include <linux/types.h>
#else
    #include <stdint.h>
#endif

#ifdef __cplusplus
#define _Static_assert static_assert
#endif

/* Cross-platform packed struct support */
#ifdef _MSC_VER
    #define PACKED_STRUCT_BEGIN __pragma(pack(push, 1))
    #define PACKED_STRUCT_END   __pragma(pack(pop))
    #define PACKED_ATTR
#else
    #define PACKED_STRUCT_BEGIN
    #define PACKED_STRUCT_END
    #define PACKED_ATTR __attribute__((packed))
#endif

#define LPU_INST_SIZE 64

/* ================================================================== */
/* LPU Instruction Opcodes                                           */
/* ================================================================== */
typedef enum {
    LPU_OP_NOP                = 0x00,  /* No operation */
    LPU_OP_HALT               = 0x01,  /* Stop execution and raise completion interrupt */
    LPU_OP_ADD                = 0x10,  /* Element-wise addition with broadcast: dst = src_a + src_b */
    LPU_OP_MUL                = 0x12,  /* Element-wise multiplication: dst = src_a * src_b */
    LPU_OP_MATMUL             = 0x20,  /* Matrix multiplication: dst = src_a @ src_b (fp16 accumulate in fp32) */
    LPU_OP_GEMM               = 0x21,  /* General matrix multiply: dst = alpha * A @ B + beta * C */
    LPU_OP_GELU               = 0x43,  /* GELU activation (Transformer standard): dst = x * 0.5 * (1 + erf(x / sqrt(2))) */
    LPU_OP_SWISH              = 0x44,  /* Swish/SiLU activation: dst = x * sigmoid(x) */
    LPU_OP_SOFTMAX            = 0x45,  /* Softmax along last axis: dst = softmax(src) */
    LPU_OP_LAYERNORM          = 0x51,  /* Layer Normalization: dst = (x - mean) / sqrt(var + eps) * gamma + beta */
    LPU_OP_RMSNORM            = 0x52,  /* RMS Normalization: dst = (x / rms(x)) * gamma (LLaMA, Qwen, PaliGemma) */
    LPU_OP_LOAD               = 0x80,  /* DMA transfer: host memory -> LPU local SRAM */
    LPU_OP_STORE              = 0x81,  /* DMA transfer: LPU local SRAM -> host memory */
    LPU_OP_PREFETCH           = 0x82,  /* Async DMA prefetch: host memory -> LPU SRAM (overlaps with compute) */
    LPU_OP_SCALED_DOT_PRODUCT_ATTENTION = 0xA0,  /* Prefill attention: dst = softmax(Q @ K^T / sqrt(d)) @ V (full sequence) */
    LPU_OP_KV_CACHE_APPEND    = 0xA1,  /* Append new K/V vectors to KV cache at current sequence position */
    LPU_OP_KV_CACHE_ATTENTION = 0xA2,  /* Decode-phase attention using cached K/V (seq_len_q=1) */
    LPU_OP_KV_CACHE_RESET     = 0xA3,  /* Reset KV cache for new sequence */
    LPU_OP_EMBEDDING_LOOKUP   = 0xC0,  /* Read a row from embedding table: dst = table[token_id] */
    LPU_OP_TOKEN_SAMPLE       = 0xC1,  /* Sample token from logits with temperature and top-k/top-p */
    LPU_OP_ROTARY_EMBEDDING   = 0xC2,  /* Apply RoPE to Q or K vectors in-place */
} lpu_opcode_t;

/* ================================================================== */
/* ACTIVATION Instructions                                   */
/* ================================================================== */

/* Element-wise addition with broadcast: dst = src_a + src_b */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0x10) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode */
    uint8_t flags;                       /* +0x02: [0]=fp16 [1]=broadcast_b */
    uint8_t reserved0;                   /* +0x03: Reserved */
    uint32_t reserved1;                  /* +0x04: Reserved */
    uint64_t src_a_addr;                 /* +0x08: LPU-local address of A */
    uint64_t src_b_addr;                 /* +0x10: LPU-local address of B */
    uint64_t dst_addr;                   /* +0x18: LPU-local address of output */
    uint32_t num_elements;               /* +0x20: Total element count */
    uint8_t reserved_pad[28];            /* +0x24: Padding to 64 bytes */
} lpu_inst_add_t;

_Static_assert(sizeof(lpu_inst_add_t) == LPU_INST_SIZE,
              "lpu_inst_add_t must be 64 bytes");

/* Element-wise multiplication: dst = src_a * src_b */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0x12) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode */
    uint8_t flags;                       /* +0x02: [0]=fp16 [1]=broadcast_b */
    uint8_t reserved0;                   /* +0x03: Reserved */
    uint32_t reserved1;                  /* +0x04: Reserved */
    uint64_t src_a_addr;                 /* +0x08: LPU-local address of A */
    uint64_t src_b_addr;                 /* +0x10: LPU-local address of B */
    uint64_t dst_addr;                   /* +0x18: LPU-local address of output */
    uint32_t num_elements;               /* +0x20: Total element count */
    uint8_t reserved_pad[28];            /* +0x24: Padding to 64 bytes */
} lpu_inst_mul_t;

_Static_assert(sizeof(lpu_inst_mul_t) == LPU_INST_SIZE,
              "lpu_inst_mul_t must be 64 bytes");

/* GELU activation (Transformer standard): dst = x * 0.5 * (1 + erf(x / sqrt(2))) */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0x43) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode */
    uint8_t flags;                       /* +0x02: [0]=fp16 */
    uint8_t reserved0;                   /* +0x03: Reserved */
    uint32_t reserved1;                  /* +0x04: Reserved */
    uint64_t src_addr;                   /* +0x08: LPU-local address of ilput */
    uint64_t dst_addr;                   /* +0x10: LPU-local address of output */
    uint32_t num_elements;               /* +0x18: Total element count */
    uint8_t reserved_pad[36];            /* +0x1C: Padding to 64 bytes */
} lpu_inst_gelu_t;

_Static_assert(sizeof(lpu_inst_gelu_t) == LPU_INST_SIZE,
              "lpu_inst_gelu_t must be 64 bytes");

/* Swish/SiLU activation: dst = x * sigmoid(x) */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0x44) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode */
    uint8_t flags;                       /* +0x02: [0]=fp16 */
    uint8_t reserved0;                   /* +0x03: Reserved */
    uint32_t reserved1;                  /* +0x04: Reserved */
    uint64_t src_addr;                   /* +0x08: LPU-local address of ilput */
    uint64_t dst_addr;                   /* +0x10: LPU-local address of output */
    uint32_t num_elements;               /* +0x18: Total element count */
    uint8_t reserved_pad[36];            /* +0x1C: Padding to 64 bytes */
} lpu_inst_swish_t;

_Static_assert(sizeof(lpu_inst_swish_t) == LPU_INST_SIZE,
              "lpu_inst_swish_t must be 64 bytes");

/* Softmax along last axis: dst = softmax(src) */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0x45) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode */
    uint8_t flags;                       /* +0x02: [0]=fp16 */
    uint8_t reserved0;                   /* +0x03: Reserved */
    uint32_t reserved1;                  /* +0x04: Reserved */
    uint64_t src_addr;                   /* +0x08: LPU-local address of ilput */
    uint64_t dst_addr;                   /* +0x10: LPU-local address of output */
    uint32_t batch_size;                 /* +0x18: Number of rows */
    uint32_t axis_size;                  /* +0x1C: Size of softmax axis */
    uint8_t reserved_pad[32];            /* +0x20: Padding to 64 bytes */
} lpu_inst_softmax_t;

_Static_assert(sizeof(lpu_inst_softmax_t) == LPU_INST_SIZE,
              "lpu_inst_softmax_t must be 64 bytes");

/* ================================================================== */
/* ATTENTION Instructions                                   */
/* ================================================================== */

/* Prefill attention: dst = softmax(Q @ K^T / sqrt(d)) @ V (full sequence) */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0xA0) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode */
    uint8_t flags;                       /* +0x02: [0]=fp16 [1]=causal_mask */
    uint8_t reserved0;                   /* +0x03: Reserved */
    uint32_t scale_fp32;                 /* +0x04: Scale factor (fp32 bit pattern), 0 = auto */
    uint64_t q_addr;                     /* +0x08: Q (num_heads × seq_len_q × head_dim) */
    uint64_t k_addr;                     /* +0x10: K (num_heads × seq_len_kv × head_dim) */
    uint64_t v_addr;                     /* +0x18: V (num_heads × seq_len_kv × head_dim) */
    uint64_t dst_addr;                   /* +0x20: Output (num_heads × seq_len_q × head_dim) */
    uint32_t num_heads;                  /* +0x28: Number of attention heads */
    uint32_t seq_len_q;                  /* +0x2C: Query sequence length */
    uint32_t seq_len_kv;                 /* +0x30: Key/Value sequence length */
    uint32_t head_dim;                   /* +0x34: Dimension per head */
    uint8_t reserved_pad[8];             /* +0x38: Padding to 64 bytes */
} lpu_inst_scaled_dot_product_attention_t;

_Static_assert(sizeof(lpu_inst_scaled_dot_product_attention_t) == LPU_INST_SIZE,
              "lpu_inst_scaled_dot_product_attention_t must be 64 bytes");

/* Append new K/V vectors to KV cache at current sequence position */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0xA1) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode */
    uint8_t flags;                       /* +0x02: [0]=fp16 [1]=grouped_query_attention */
    uint8_t reserved0;                   /* +0x03: Reserved */
    uint32_t reserved1;                  /* +0x04: Reserved */
    uint64_t k_new_addr;                 /* +0x08: New K vector (num_kv_heads × head_dim) */
    uint64_t v_new_addr;                 /* +0x10: New V vector (num_kv_heads × head_dim) */
    uint64_t k_cache_addr;               /* +0x18: K cache base (num_kv_heads × max_seq_len × head_dim) */
    uint64_t v_cache_addr;               /* +0x20: V cache base (num_kv_heads × max_seq_len × head_dim) */
    uint32_t cur_seq_pos;                /* +0x28: Current write position */
    uint16_t num_kv_heads;               /* +0x2C: Number of KV heads */
    uint16_t head_dim;                   /* +0x2E: Dimension per head */
    uint32_t max_seq_len;                /* +0x30: Maximum cache capacity */
    uint8_t reserved_pad[12];            /* +0x34: Padding to 64 bytes */
} lpu_inst_kv_cache_append_t;

_Static_assert(sizeof(lpu_inst_kv_cache_append_t) == LPU_INST_SIZE,
              "lpu_inst_kv_cache_append_t must be 64 bytes");

/* Decode-phase attention using cached K/V (seq_len_q=1) */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0xA2) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode */
    uint8_t flags;                       /* +0x02: [0]=fp16 [1]=causal_mask */
    uint8_t reserved0;                   /* +0x03: Reserved */
    uint32_t scale_fp32;                 /* +0x04: Scale factor (fp32 bit pattern), 0 = auto */
    uint64_t q_addr;                     /* +0x08: Q (num_heads × 1 × head_dim) */
    uint64_t k_cache_addr;               /* +0x10: K cache base */
    uint64_t v_cache_addr;               /* +0x18: V cache base */
    uint64_t dst_addr;                   /* +0x20: Output (num_heads × 1 × head_dim) */
    uint16_t num_heads;                  /* +0x28: Query head count */
    uint16_t num_kv_heads;               /* +0x2A: KV head count (for GQA) */
    uint32_t cur_seq_len;                /* +0x2C: Valid cache length */
    uint16_t head_dim;                   /* +0x30: Dimension per head */
    uint16_t max_seq_len;                /* +0x32: Maximum cache capacity */
    uint8_t reserved_pad[12];            /* +0x34: Padding to 64 bytes */
} lpu_inst_kv_cache_attention_t;

_Static_assert(sizeof(lpu_inst_kv_cache_attention_t) == LPU_INST_SIZE,
              "lpu_inst_kv_cache_attention_t must be 64 bytes");

/* Reset KV cache for new sequence */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0xA3) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode */
    uint8_t flags;                       /* +0x02: [0]=zero_memory */
    uint8_t reserved0;                   /* +0x03: Reserved */
    uint32_t reserved1;                  /* +0x04: Reserved */
    uint64_t k_cache_addr;               /* +0x08: K cache base */
    uint64_t v_cache_addr;               /* +0x10: V cache base */
    uint16_t num_kv_heads;               /* +0x18: Number of KV heads */
    uint16_t head_dim;                   /* +0x1A: Dimension per head */
    uint32_t max_seq_len;                /* +0x1C: Maximum cache capacity */
    uint8_t reserved_pad[32];            /* +0x20: Padding to 64 bytes */
} lpu_inst_kv_cache_reset_t;

_Static_assert(sizeof(lpu_inst_kv_cache_reset_t) == LPU_INST_SIZE,
              "lpu_inst_kv_cache_reset_t must be 64 bytes");

/* ================================================================== */
/* CONTROL Instructions                                   */
/* ================================================================== */

/* No operation */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0x00) */
    uint8_t reserved_pad[63];            /* +0x01: Padding to 64 bytes */
} lpu_inst_nop_t;

_Static_assert(sizeof(lpu_inst_nop_t) == LPU_INST_SIZE,
              "lpu_inst_nop_t must be 64 bytes");

/* Stop execution and raise completion interrupt */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0x01) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode */
    uint8_t flags;                       /* +0x02: [0]=raise_irq */
    uint8_t reserved0;                   /* +0x03: Reserved */
    uint16_t exit_code;                  /* +0x04: Exit status */
    uint8_t reserved_pad[58];            /* +0x06: Padding to 64 bytes */
} lpu_inst_halt_t;

_Static_assert(sizeof(lpu_inst_halt_t) == LPU_INST_SIZE,
              "lpu_inst_halt_t must be 64 bytes");

/* ================================================================== */
/* LINALG Instructions                                   */
/* ================================================================== */

/* Matrix multiplication: dst = src_a @ src_b (fp16 accumulate in fp32) */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0x20) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode */
    uint8_t flags;                       /* +0x02: [0]=fp16 [1]=accumulate [2]=transpose_a [3]=transpose_b */
    uint8_t reserved0;                   /* +0x03: Reserved */
    uint32_t reserved1;                  /* +0x04: Reserved */
    uint64_t src_a_addr;                 /* +0x08: LPU-local address of matrix A (M × K) */
    uint64_t src_b_addr;                 /* +0x10: LPU-local address of matrix B (K × N) */
    uint64_t dst_addr;                   /* +0x18: LPU-local address of result C (M × N) */
    uint32_t m;                          /* +0x20: Rows of A / rows of C */
    uint32_t n;                          /* +0x24: Cols of B / cols of C */
    uint32_t k;                          /* +0x28: Cols of A / rows of B */
    uint8_t reserved_pad[20];            /* +0x2C: Padding to 64 bytes */
} lpu_inst_matmul_t;

_Static_assert(sizeof(lpu_inst_matmul_t) == LPU_INST_SIZE,
              "lpu_inst_matmul_t must be 64 bytes");

/* General matrix multiply: dst = alpha * A @ B + beta * C */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0x21) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode */
    uint8_t flags;                       /* +0x02: [0]=fp16 [1]=transpose_a [2]=transpose_b [3]=has_bias */
    uint8_t reserved0;                   /* +0x03: Reserved */
    uint16_t alpha_fp16;                 /* +0x04: Alpha scalar (fp16 bit pattern) */
    uint16_t beta_fp16;                  /* +0x06: Beta scalar (fp16 bit pattern) */
    uint64_t src_a_addr;                 /* +0x08: LPU-local address of A */
    uint64_t src_b_addr;                 /* +0x10: LPU-local address of B */
    uint64_t bias_addr;                  /* +0x18: LPU-local address of bias C (0 if none) */
    uint64_t dst_addr;                   /* +0x20: LPU-local address of result */
    uint32_t m;                          /* +0x28: Rows */
    uint32_t n;                          /* +0x2C: Cols */
    uint32_t k;                          /* +0x30: Inner dimension */
    uint8_t reserved_pad[12];            /* +0x34: Padding to 64 bytes */
} lpu_inst_gemm_t;

_Static_assert(sizeof(lpu_inst_gemm_t) == LPU_INST_SIZE,
              "lpu_inst_gemm_t must be 64 bytes");

/* ================================================================== */
/* MEMORY Instructions                                   */
/* ================================================================== */

/* DMA transfer: host memory -> LPU local SRAM */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0x80) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode */
    uint8_t flags;                       /* +0x02: [0]=async [1]=notify_on_complete */
    uint8_t reserved0;                   /* +0x03: Reserved */
    uint32_t reserved1;                  /* +0x04: Reserved */
    uint64_t host_addr;                  /* +0x08: Host physical/IOVA address (source) */
    uint64_t lpu_addr;                   /* +0x10: LPU-local SRAM address (destination) */
    uint32_t size_bytes;                 /* +0x18: Number of bytes to transfer */
    uint8_t reserved_pad[36];            /* +0x1C: Padding to 64 bytes */
} lpu_inst_load_t;

_Static_assert(sizeof(lpu_inst_load_t) == LPU_INST_SIZE,
              "lpu_inst_load_t must be 64 bytes");

/* DMA transfer: LPU local SRAM -> host memory */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0x81) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode */
    uint8_t flags;                       /* +0x02: [0]=async [1]=notify_on_complete */
    uint8_t reserved0;                   /* +0x03: Reserved */
    uint32_t reserved1;                  /* +0x04: Reserved */
    uint64_t lpu_addr;                   /* +0x08: LPU-local SRAM address (source) */
    uint64_t host_addr;                  /* +0x10: Host physical/IOVA address (destination) */
    uint32_t size_bytes;                 /* +0x18: Number of bytes to transfer */
    uint8_t reserved_pad[36];            /* +0x1C: Padding to 64 bytes */
} lpu_inst_store_t;

_Static_assert(sizeof(lpu_inst_store_t) == LPU_INST_SIZE,
              "lpu_inst_store_t must be 64 bytes");

/* Async DMA prefetch: host memory -> LPU SRAM (overlaps with compute) */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0x82) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode */
    uint8_t flags;                       /* +0x02: [0]=async [1]=notify_on_complete [2]=prefetch_hint */
    uint8_t tag;                         /* +0x03: Prefetch tag for tracking completion (0-255) */
    uint32_t reserved1;                  /* +0x04: Reserved */
    uint64_t host_addr;                  /* +0x08: Host physical/IOVA address (source) */
    uint64_t lpu_addr;                   /* +0x10: LPU-local SRAM address (destination) */
    uint32_t size_bytes;                 /* +0x18: Number of bytes to transfer */
    uint8_t reserved_pad[36];            /* +0x1C: Padding to 64 bytes */
} lpu_inst_prefetch_t;

_Static_assert(sizeof(lpu_inst_prefetch_t) == LPU_INST_SIZE,
              "lpu_inst_prefetch_t must be 64 bytes");

/* ================================================================== */
/* NORMALIZATION Instructions                                   */
/* ================================================================== */

/* Layer Normalization: dst = (x - mean) / sqrt(var + eps) * gamma + beta */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0x51) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode */
    uint8_t flags;                       /* +0x02: [0]=fp16 [1]=has_bias */
    uint8_t reserved0;                   /* +0x03: Reserved */
    uint32_t eps_fp32;                   /* +0x04: Epsilon (fp32 bit pattern) */
    uint64_t src_addr;                   /* +0x08: LPU-local address of ilput */
    uint64_t gamma_addr;                 /* +0x10: LPU-local address of gamma */
    uint64_t beta_addr;                  /* +0x18: LPU-local address of beta (0 if no bias) */
    uint64_t dst_addr;                   /* +0x20: LPU-local address of output */
    uint32_t batch_size;                 /* +0x28: Batch dimension */
    uint32_t hidden_size;                /* +0x2C: Hidden dimension */
    uint8_t reserved_pad[16];            /* +0x30: Padding to 64 bytes */
} lpu_inst_layernorm_t;

_Static_assert(sizeof(lpu_inst_layernorm_t) == LPU_INST_SIZE,
              "lpu_inst_layernorm_t must be 64 bytes");

/* RMS Normalization: dst = (x / rms(x)) * gamma (LLaMA, Qwen, PaliGemma) */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0x52) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode */
    uint8_t flags;                       /* +0x02: [0]=fp16 */
    uint8_t reserved0;                   /* +0x03: Reserved */
    uint32_t eps_fp32;                   /* +0x04: Epsilon (fp32 bit pattern) */
    uint64_t src_addr;                   /* +0x08: LPU-local address of ilput (batch × hidden) */
    uint64_t gamma_addr;                 /* +0x10: LPU-local address of gamma scale (hidden,) */
    uint64_t dst_addr;                   /* +0x18: LPU-local address of output */
    uint32_t batch_size;                 /* +0x20: Batch dimension */
    uint32_t hidden_size;                /* +0x24: Hidden dimension (normalization axis) */
    uint8_t reserved_pad[24];            /* +0x28: Padding to 64 bytes */
} lpu_inst_rmsnorm_t;

_Static_assert(sizeof(lpu_inst_rmsnorm_t) == LPU_INST_SIZE,
              "lpu_inst_rmsnorm_t must be 64 bytes");

/* ================================================================== */
/* TOKEN Instructions                                   */
/* ================================================================== */

/* Read a row from embedding table: dst = table[token_id] */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0xC0) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode */
    uint8_t flags;                       /* +0x02: [0]=fp16 */
    uint8_t reserved0;                   /* +0x03: Reserved */
    uint32_t token_id;                   /* +0x04: Ilput token ID */
    uint64_t table_addr;                 /* +0x08: Embedding table base (vocab × embed_dim) */
    uint64_t dst_addr;                   /* +0x10: Output embedding vector */
    uint32_t vocab_size;                 /* +0x18: Vocabulary size */
    uint32_t embed_dim;                  /* +0x1C: Embedding dimension */
    uint8_t reserved_pad[32];            /* +0x20: Padding to 64 bytes */
} lpu_inst_embedding_lookup_t;

_Static_assert(sizeof(lpu_inst_embedding_lookup_t) == LPU_INST_SIZE,
              "lpu_inst_embedding_lookup_t must be 64 bytes");

/* Sample token from logits with temperature and top-k/top-p */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0xC1) */
    uint8_t sub_opcode;                  /* +0x01: 0=greedy 1=top_k 2=top_p */
    uint8_t flags;                       /* +0x02: [0]=fp16 */
    uint8_t reserved0;                   /* +0x03: Reserved */
    uint32_t temperature_fp32;           /* +0x04: Temperature (fp32 bits) */
    uint64_t logits_addr;                /* +0x08: Logits vector */
    uint64_t dst_token_addr;             /* +0x10: Output token ID (u32) */
    uint32_t vocab_size;                 /* +0x18: Logits size */
    uint16_t top_k;                      /* +0x1C: Top-k (0=disabled) */
    uint16_t reserved1;                  /* +0x1E: Reserved */
    uint32_t seed;                       /* +0x20: RNG seed */
    uint8_t reserved_pad[28];            /* +0x24: Padding to 64 bytes */
} lpu_inst_token_sample_t;

_Static_assert(sizeof(lpu_inst_token_sample_t) == LPU_INST_SIZE,
              "lpu_inst_token_sample_t must be 64 bytes");

/* Apply RoPE to Q or K vectors in-place */
typedef struct __attribute__((packed)) {
    uint8_t opcode;                      /* +0x00: Opcode (0xC2) */
    uint8_t sub_opcode;                  /* +0x01: Sub-opcode */
    uint8_t flags;                       /* +0x02: [0]=fp16 [1]=neox_style */
    uint8_t reserved0;                   /* +0x03: Reserved */
    uint32_t position;                   /* +0x04: Sequence position */
    uint64_t src_addr;                   /* +0x08: Ilput Q or K (num_heads × head_dim) */
    uint64_t dst_addr;                   /* +0x10: Output (can be same for in-place) */
    uint16_t num_heads;                  /* +0x18: Number of heads */
    uint16_t head_dim;                   /* +0x1A: Dimension per head (must be even) */
    uint32_t theta_base_fp32;            /* +0x1C: Base frequency (fp32 bits), typically 10000.0 */
    uint8_t reserved_pad[32];            /* +0x20: Padding to 64 bytes */
} lpu_inst_rotary_embedding_t;

_Static_assert(sizeof(lpu_inst_rotary_embedding_t) == LPU_INST_SIZE,
              "lpu_inst_rotary_embedding_t must be 64 bytes");

/* ================================================================== */
/* Generic Instruction (for fetch/decode)                             */
/* ================================================================== */
typedef union __attribute__((packed)) {
    uint8_t  opcode;                       /* First byte is always opcode */
    uint8_t  raw[LPU_INST_SIZE];           /* Raw byte access */
    lpu_inst_nop_t                       nop;
    lpu_inst_halt_t                      halt;
    lpu_inst_add_t                       add;
    lpu_inst_mul_t                       mul;
    lpu_inst_matmul_t                    matmul;
    lpu_inst_gemm_t                      gemm;
    lpu_inst_gelu_t                      gelu;
    lpu_inst_swish_t                     swish;
    lpu_inst_softmax_t                   softmax;
    lpu_inst_layernorm_t                 layernorm;
    lpu_inst_rmsnorm_t                   rmsnorm;
    lpu_inst_load_t                      load;
    lpu_inst_store_t                     store;
    lpu_inst_prefetch_t                  prefetch;
    lpu_inst_scaled_dot_product_attention_t scaled_dot_product_attention;
    lpu_inst_kv_cache_append_t           kv_cache_append;
    lpu_inst_kv_cache_attention_t        kv_cache_attention;
    lpu_inst_kv_cache_reset_t            kv_cache_reset;
    lpu_inst_embedding_lookup_t          embedding_lookup;
    lpu_inst_token_sample_t              token_sample;
    lpu_inst_rotary_embedding_t          rotary_embedding;
} lpu_inst_t;

_Static_assert(sizeof(lpu_inst_t) == LPU_INST_SIZE,
              "lpu_inst_t must be 64 bytes");

#define LPU_OPCODE_COUNT 21

#endif /* UNAF_LPU_SPEC_H */
